# This is a basic workflow to help you get started with Actions

name: CI-aaad

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on    
    runs-on: musescore/musescore-x86_64:latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: PDF conversion
        run: for scores in $GITHUB_WORKSPACE/**/*mscx ; do mscore -o $(dirname $score)'/pdf/'$(basename $score .mdcx)'.pdf' $score; done
        
  publish:
    runs-on: 
    steps:
      - name: Publish to GitHub Wiki
        # You may pin to the exact commit or the version.
        # uses: SwiftDocOrg/github-wiki-publish-action@a87db85ed06e4431be29cfdcb22b9653881305d0
        uses: SwiftDocOrg/github-wiki-publish-action@1.0.0
        with:
          # A path to the directory of files to publish
          path: $GITHUB_WORKSPACE/**/*
  
